### ISSUE TITLE
RNN cell reset done one step too late ...

### ISSUE THREAD

**Issue by andreiionutdamian** [pcerdam/KerasGRU4Rec#1]
Hi there,
As it seems your training generator basically generates the data so that for each batch you receive the reset mask at the beginning of the batch. To be more precise here are some examples:
```
Mask: []
Rest: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Feat: [ 0  4  9 12 14 16 18 19 20 29]
Trgt: [ 1  4 10 13 15 17 18 19 20 29]

Mask: [3 4 5 6 9]
Rest: [0. 0. 0. 1. 1. 1. 1. 0. 0. 1.]
Feat: [ 1  4 10 30 32 36 34 19 20 32]
Trgt: [ 2  5 11 31 33 36 35 19 21 32]
```
As you can see from the generated data the model has to reset the RNN cells states prior to the fw/bp passes done in the train_on_batch, otherwise the reset will be done after the current session last step is "connected" to the next session first step. However in your code you are resetting the RNN cells after the train_on_batch.

**Comment by pcerdam** [comment]
Hello Andrei,

Apologies for my late response, it seems I wasn't "watching" the repository, and so I noticed this issue today.

You are absolutely right, to be honest I'm not sure when this bug was introduced on our implementation. In practice, this means that whenever there's a session replacement, the cell will learn that one step with an inherited (and unwanted) state, and given that session switches are fairly common events, I'm guessing results will be impacted in a noticeable way. 

I'm currently training the model with this issue fixed, as soon as I can get a better idea of how it was affecting the performance I'll report it here. You can expect the fixed implementation to be pushed as well.

Thanks for your observation!

**Comment by andreidi** [comment]
> Hello Andrei,
> 
> Apologies for my late response, it seems I wasn't "watching" the repository, and so I only noticed this issue today.
> 
> You are absolutely right, to be honest I'm not sure when this bug was introduced on our implementation. In practice, this means that whenever there's a session replacement, the cell will learn that one step with an inherited (and unwanted) state, and given that session switches are fairly common events, I'm guessing results will be impacted in a noticeable way.
> 
> I'm currently training the model with this issue fixed, as soon as I can get a better idea of how it was affecting the performance I'll report it here. You can expect the fixed implementation to be pushed as well.
> 
> Thanks for your observation!

Your are welcome, pleasure was mine. 
This should have "nudged" the results a wee bit, but not a lot, as it only basically introduced noise in the correct labeling from time to time.

**Comment by pcerdam** [comment]
Indeed,

after training with this bug fixed, the model now presents the following results:

Precision@20: 0.685397
MRR@20:        0.294843
